apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-new-deployment  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: new-project
  template:
    metadata:
      labels:
        app: new-project
    spec:
      containers:
        - name: my-container
          image: yousseframadan676/ssss
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
